" Pathogen
  execute pathogen#infect()

" Leader
  let mapleader=","

" Basics
  syntax on
  imap jj <esc>
  set number
  set laststatus=2
  set ruler
  set pastetoggle=<F10>
  set nocompatible
  set cursorline
  set wildmenu
  set showmode

" All the backspaces!
  set backspace=indent,eol,start

" Centralize backups, swapfiles and undo history
  set backupdir=~/.vim/backups
  set directory=~/.vim/swaps

" For MacVim
  set guifont=Inconsolata:h17

" Colours
  colorscheme Tomorrow-Night-Bright

" Filetypes
  au BufNewFile,BufRead Vagrantfile set filetype=ruby
  au BufNewFile,BufRead Gemfile set filetype=ruby

" Tabs and whitespace
  set expandtab
  set tabstop=2
  set shiftwidth=2

" Searching
  set hlsearch
  set incsearch
  set ignorecase

" Nuke arrow keys
  map <Left> <Nop>
  map <Right> <Nop>
  map <Up> <Nop>
  map <Down> <Nop>

" Pathogen
  "execute pathogen#infect()
  "let g:airline_powerline_fonts = 1
