" Leader
  let mapleader=","

" ctrlp
  set runtimepath^=~/.vim/bundle/ctrlp.vim

" Basics
  set term=screen-256color
  syntax on
  imap jj <esc>
  set number
  set laststatus=2
  set ruler
  set pastetoggle=<F10>
  set nocompatible
  set cursorline
  set wildmenu
  set showmode
  set nowrap
  set colorcolumn=80

" All the backspaces!
  set backspace=indent,eol,start

" Centralize backups, swapfiles and undo history
  set backupdir=~/.vim/backups
  set directory=~/.vim/swaps

" Colours
  colorscheme Tomorrow-Night-Bright

" Filetypes
  au BufNewFile,BufRead Vagrantfile set filetype=ruby
  au BufNewFile,BufRead Gemfile set filetype=ruby

" Tabs and whitespace
  set expandtab
  set tabstop=2
  set shiftwidth=2

" Searching
  set hlsearch
  set incsearch
  set ignorecase

" Nuke arrow keys
  map <Left> <Nop>
  map <Right> <Nop>
  map <Up> <Nop>
  map <Down> <Nop>

" ctrl-p
  let g:ctrlp_user_command = ['.git/', 'git --git-dir=%s/.git ls-files -oc --exclude-standard']

" fancy cursor
  " let &t_SI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=1\x7\<Esc>\\"
  " let &t_EI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=0\x7\<Esc>\\"

" nerdtree
  map <C-n> :NERDTreeToggle<CR>
