# zsh
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="samstarling"
plugins=(osx git)
source $ZSH/oh-my-zsh.sh

# rbenv
export PATH="/Users/samstarling/.rbenv/shims:$PATH"
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# heroku
export PATH="/usr/local/heroku/bin:$PATH"

# z for rapid directory switching
source `brew --prefix`/etc/profile.d/z.sh

# jenv
export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"

# boot2docker
eval $(boot2docker shellinit 2>/dev/null)

# other bits
export EDITOR="vim"
export TERM="screen-256color"

