# zsh
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="samstarling"
plugins=(osx git)
source $ZSH/oh-my-zsh.sh

# rbenv
export PATH="/Users/samstarling/.rbenv/shims:$PATH"
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# heroku
export PATH="/usr/local/heroku/bin:$PATH"

# z for rapid directory switching
source `brew --prefix`/etc/profile.d/z.sh

# jenv
export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"

# other bits
export EDITOR="vim"
export TERM="screen-256color"

# go
export GOPATH="/Users/samuelstarling/Development/go"
export PATH="$PATH:$GOPATH/bin"

# brew
export PATH="/usr/local/sbin:$PATH"

# docker-machine
eval "$(docker-machine env default)"

function bazooka-procs {
  bazooka ps | tr -s ' ' | cut -d' ' -f4-5 | grep -v 'REV ENV' | sort | uniq -c
}

export NVM_DIR="/Users/samuelstarling/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
